/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hardwarestore.view.customer;

import com.mycompany.hardwarestore.model.CartItem;
import com.mycompany.hardwarestore.service.CartService;

import javax.swing.JOptionPane;
import java.util.List;

import javax.swing.table.DefaultTableModel;
import com.mycompany.hardwarestore.model.User;

import com.mycompany.hardwarestore.dao.CustomerDAO;
import com.mycompany.hardwarestore.service.CheckoutService;

/**
 *
 * @author navod
 */
public class CartPanel extends javax.swing.JPanel {

    /**
     * Creates new form CartPanel
     */
    private final CartService cartService;
    private final User loggedInUser;

    private final CustomerDAO customerDAO = new CustomerDAO();
    private final CheckoutService checkoutService = new CheckoutService();

    public CartPanel(
            CartService cartService,
            User loggedInUser) {

        this.cartService = cartService;
        this.loggedInUser = loggedInUser;

        initComponents();
        loadCart();
    }

    private void loadCart() {

        List<CartItem> cartItems = cartService.getCartItems();

        DefaultTableModel model
                = (DefaultTableModel) tblCart.getModel();

        model.setRowCount(0);

        double total = 0;

        for (CartItem item : cartItems) {

            model.addRow(new Object[]{
                item.getProduct().getProductName(),
                String.format("LKR %,.2f",
                item.getProduct().getPrice()),
                item.getQuantity(),
                String.format("LKR %,.2f",
                item.getSubtotal())
            });

            total += item.getSubtotal();
        }

        lblTotal.setText(
                String.format("LKR %,.2f", total)
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnClearCart = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();

        jLabel1.setText("Shopping Cart");

        jLabel2.setText("Review your items before checkout");

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblCart);

        jLabel3.setText("Total:");

        lblTotal.setText("LKR 25,000.00");

        btnRemove.setText("Remove Item");
        btnRemove.addActionListener(this::btnRemoveActionPerformed);

        btnClearCart.setText("Clear cart");
        btnClearCart.addActionListener(this::btnClearCartActionPerformed);

        btnCheckout.setText("Proceed to checkout");
        btnCheckout.addActionListener(this::btnCheckoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(lblTotal)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCheckout)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(btnRemove)
                            .addGap(50, 50, 50)
                            .addComponent(btnClearCart))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotal))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(btnClearCart))
                .addGap(36, 36, 36)
                .addComponent(btnCheckout)
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCart.getSelectedRow();

        if (selectedRow == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select an item from the cart first.",
                    "No Item Selected",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        CartItem selectedItem
                = cartService.getCartItems().get(selectedRow);

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Remove "
                + selectedItem.getProduct().getProductName()
                + " from the cart?",
                "Remove Item",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {

            cartService.removeItem(
                    selectedItem.getProduct().getProductId()
            );

            loadCart();
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCartActionPerformed
        // TODO add your handling code here:
        if (cartService.getCartItems().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "The cart is already empty.",
                    "Cart",
                    JOptionPane.INFORMATION_MESSAGE
            );

            return;
        }

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to clear the entire cart?",
                "Clear Cart",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {

            cartService.clearCart();

            loadCart();
        }
    }//GEN-LAST:event_btnClearCartActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
        if (cartService.getCartItems().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Your cart is empty.",
                    "Checkout",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }
        String[] paymentOptions = {
            "CASH",
            "CARD"
        };

        String paymentMethod
                = (String) JOptionPane.showInputDialog(
                        this,
                        "Select payment method:",
                        "Checkout",
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        paymentOptions,
                        paymentOptions[0]
                );

        try {

            int customerId
                    = customerDAO.getCustomerIdByUserId(
                            loggedInUser.getUserId()
                    );
            if (customerId == -1) {

                JOptionPane.showMessageDialog(
                        this,
                        "Customer account could not be found.",
                        "Checkout Error",
                        JOptionPane.ERROR_MESSAGE
                );

                return;
            }
            int orderId = checkoutService.checkout(
                    customerId,
                    cartService.getCartItems(),
                    paymentMethod
            );
            JOptionPane.showMessageDialog(
                    this,
                    "Payment Successful!\n"
                    + "Order ID: " + orderId,
                    "Order Completed",
                    JOptionPane.INFORMATION_MESSAGE
            );
            cartService.clearCart();
            loadCart();
        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Checkout Error",
                    JOptionPane.WARNING_MESSAGE
            );

        } catch (java.sql.SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Checkout failed.\n"
                    + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnClearCart;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCart;
    // End of variables declaration//GEN-END:variables
}
